name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  'jagan'
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: pwsh
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: pwsh
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: pwsh
    - run: goodbye.ps1
      shell: pwsh
